pipeline {
    agent {
        docker {
            image 'hashicorp/terraform:1.7.5'
            args '-u root' // avoids permission issues
        }
    }

    parameters {
        choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Terraform action')
        string(name: 'WORKSPACE', defaultValue: 'default', description: 'Terraform workspace')
        text(name: 'Preview', defaultValue: "See tfplan artifact after plan stage")
    }

    environment {
        ECR_REPO   = "503499294473.dkr.ecr.us-east-1.amazonaws.com/mynode"
        AWS_REGION = "us-east-1"
        TF_DIR     = "terraform"
    }

    stages {
        stage('Terraform') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-jenkins-creds'
                ]]) {

                    dir(env.TF_DIR) {

                        sh '''
                            terraform init -input=false

                            terraform workspace select ${WORKSPACE} 2>/dev/null || \
                            terraform workspace new ${WORKSPACE}

                            terraform plan -out=tfplan
                        '''

                        script {
                            if (params.ACTION != 'plan') {

                                input message: "Approve ${params.ACTION}?"

                                if (params.ACTION == 'apply') {
                                    sh "terraform apply -auto-approve tfplan"
                                } else {
                                    sh "terraform destroy -auto-approve"
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        success { echo "Pipeline succeeded" }
        failure { echo "Pipeline failed" }
        always  { cleanWs() }
    }
}
