pipeline {
    agent any

    parameters {
        choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Terraform action')
        string(name: 'WORKSPACE', defaultValue: 'default', description: 'Terraform workspace')
    }

    environment {
        ECR_REPO   = "503499294473.dkr.ecr.us-east-1.amazonaws.com/mynode"
        AWS_REGION = "us-east-1"
    }

    stages {
        stage('Terraform') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-jenkins-creds'
                ]]) {
                    dir(TF_DIR) {
                        sh """
                            terraform init -input=false
                        """

                        script {
                            if (params.ACTION != 'plan') {
                                input message: "Approve ${params.ACTION}?", ok: "Proceed",
                                      parameters: [text(name: 'Preview', defaultValue: readFile('tfplan.txt'))]

                                sh params.ACTION == 'apply'
                                    ? "terraform apply -auto-approve tfplan"
                                    : "terraform destroy -auto-approve"
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always  { cleanWs() }
        success { echo "✅ Pushed $ECR_REPO:$DOCKER_TAG" }
        failure { echo "❌ Pipeline failed!" }
    }
}